In [1]:
import numpy as np

def calc_weight(X, Y):
    return np.dot(X.T, Y)

def bipolar_activation(matrix):
    return np.where(matrix > 0, 1, -1)

def forward(Y, weight):
    return bipolar_activation(np.dot(Y, weight.T))

def backward(X, weight):
    return bipolar_activation(np.dot(X, weight))

# Define all 4 vector pairs
X = np.array([
    [1, 1, 1, 1, 1, 1],
    [-1, -1, -1, -1, -1, -1],
    [1, -1, -1, 1, 1, 1],
    [1, 1, -1, -1, -1, -1]
])

Y = np.array([
    [1, 1, 1],
    [-1, -1, -1],
    [-1, 1, 1],
    [1, -1, 1]
])

# Calculate weight matrix
W = calc_weight(X, Y)
print("Weight Matrix:\n", W)

# Forward Test
print("\nForward Testing:")
for i in range(len(Y)):
    print(f"Y{i+1} ->", forward(Y[i], W), "Expected X", i+1)

# Backward Test
print("\nBackward Testing:")
for i in range(len(X)):
    print(f"X{i+1} ->", backward(X[i], W), "Expected Y", i+1)


Weight Matrix:
 [[2 2 4]
 [4 0 2]
 [2 2 0]
 [0 4 2]
 [0 4 2]
 [0 4 2]]

Forward Testing:
Y1 -> [1 1 1 1 1 1] Expected X 1
Y2 -> [-1 -1 -1 -1 -1 -1] Expected X 2
Y3 -> [ 1 -1 -1  1  1  1] Expected X 3
Y4 -> [ 1  1 -1 -1 -1 -1] Expected X 4

Backward Testing:
X1 -> [1 1 1] Expected Y 1
X2 -> [-1 -1 -1] Expected Y 2
X3 -> [-1  1  1] Expected Y 3
X4 -> [ 1 -1 -1] Expected Y 4
