In [18]:
import numpy as np

class ART:
    def __init__(self, data, rho):
        self.data = data
        self.rho = rho
        self.weights = []
    
    def match(self, x, w):
        return np.sum(np.minimum(x, w)) / np.sum(x) >= self.rho

    def train(self):
        for x in self.data:
            for i, w in enumerate(self.weights):
                if self.match(x, w):
                    self.weights[i] = np.minimum(w, x)
                    break
            else:
                self.weights.append(x)

    def predict(self, x):
        for i, w in enumerate(self.weights):
            if self.match(x, w):
                return i
        return -1

patterns = np.array([
    [1,0,0,0,1,0,1],
    [0,1,0,0,0,1,1],
    [0,0,1,0,1,1,0],
    [0,0,0,1,0,1,1]
])

net = ART(patterns, rho=0.7)
net.train()

tests = np.array([
    [1,0,0,0,1,0,1],
    [0,1,0,0,0,1,1],
    [0,0,1,0,1,1,0],
    [0,0,0,1,0,1,1],
    [1,1,0,0,0,1,0],
    [0,0,0,0,0,0,1]
])


print("Input Pattern\t\tMatched Cluster")
print("-----------------------------------")

for x in tests:
    print(f"{x}         Cluster {net.predict(x)}")
# for pattern in test_patterns:
#     matched_cluster = network.predict(pattern)
#     print(f"{pattern}\t\t{matched_cluster}")

Input Pattern		Matched Cluster
-----------------------------------
[1 0 0 0 1 0 1]         Cluster 0
[0 1 0 0 0 1 1]         Cluster 1
[0 0 1 0 1 1 0]         Cluster 2
[0 0 0 1 0 1 1]         Cluster 3
[1 1 0 0 0 1 0]         Cluster -1
[0 0 0 0 0 0 1]         Cluster 0
